<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

# Neural Networks

## *Data Science Unit 4 Sprint 2 Assignment 1*

## Define the Following:
You can add image, diagrams, whatever you need to ensure that you understand the concepts below.

### Input Layer:

Recieves input from the dataset. The 'first' or leftmost layer in a neural network. Typically node maps are drawn with one input for each of the different inputs/featur        es/columns in a dataset. 

### Hidden Lay

Refers to all the layers between the input and output layers. "Deep learning" effectively refers to using a neural network that has muliple hidden layers.
### Output Layer:

The final ('rightmost') layer. Typically the output layer outputs a vector of values in a format suitable for the type of problem to be addressed. Often the output value is modified by an 'activation function' to transform it into a format that makes sense for a given context.

### Neuron:

A neuron (aka. a node) takes all the inputs, performs some action (typically using the weights) and then applies an activation function (typically the function is used within one layer) and produces an output.

### Weight:

Weights are the coefficients that inputs are multiplied by within a neuron. Optimal weights can be found through gradient descent if there is a loss function that evaluates the quality of our predictions compared to the targets in the training data.

### Activation Function:

Activation functions decide how much signal is passed onto the next layer (how on or off the node is). Each node in a given layer typically has the same activation function. Activation functions are sometimes referred to as transfer functions because they determine how much signal is transferred to the next layer.

### Node Map:


A node map is a simple diagram which visually explains how a node within a neural network is computed. Node maps typically show the input, hidden, output layers, and the connections between each layer.

### Perceptron:

A percepron is a single node or neuron of a neural network. A perceptron takes any number of inputs and produces an output. Essentially a neuron takes each input values, multiplies it by a weight, sums all the products, and passes the sum through an activation function which produces the final value.

## Inputs -> Outputs

### Explain the flow of information through a neural network from inputs to outputs. Be sure to include: inputs, weights, bias, and activation functions. How does it all flow from beginning to end?

#### Your Answer Here

## Write your own perceptron code that can correctly classify (99.0% accuracy) a NAND gate. 

| x1 | x2 | y |
|----|----|---|
| 0  | 0  | 1 |
| 1  | 0  | 1 |
| 0  | 1  | 1 |
| 1  | 1  | 0 |

In [6]:
import numpy as np


In [2]:
import pandas as pd
data = { 'x1': [0,1,0,1],
         'x2': [0,0,1,1],
         'y':  [1,1,1,0]
       }

df = pd.DataFrame.from_dict(data).astype('int')

In [3]:
##### Your Code Here #####
X = df.loc[:,['x1','x2']].values
X

array([[0, 0],
       [1, 0],
       [0, 1],
       [1, 1]])

In [4]:
def sigmoid(x):
    return 1 / (1+np.exp(-x))

# used to update weights
def sigmoid_derivate(x):
    sx = sigmoid(x)
    return sx * (1 - sx)

In [7]:
weights = 2 * np.random.random((2,1)) - 1
weights

array([[ 0.07126719],
       [-0.19195602]])

In [8]:
weighted_sum = np.dot(X, weights)
weighted_sum

array([[ 0.        ],
       [ 0.07126719],
       [-0.19195602],
       [-0.12068882]])

In [9]:
activated_output = sigmoid(weighted_sum)
activated_output

array([[0.5       ],
       [0.51780926],
       [0.45215781],
       [0.46986436]])

In [10]:
correct = df['y'].values
correct = [[i] for i in correct]
correct

[[1], [1], [1], [0]]

In [11]:
error = correct - activated_output
error

array([[ 0.5       ],
       [ 0.48219074],
       [ 0.54784219],
       [-0.46986436]])

In [12]:
adjustments = error * sigmoid_derivate(activated_output)
adjustments

array([[ 0.11750186],
       [ 0.11281503],
       [ 0.13019207],
       [-0.11121407]])

In [13]:
weights += np.dot(X.T, adjustments)

In [14]:
for i in range(10000):
    weighted_sum = np.dot(X, weights)
    activated_output = sigmoid(weighted_sum)
    error = correct - activated_output
    adjustments = error * sigmoid_derivate(activated_output)
    weights += np.dot(X.T, adjustments)
    
print("Weights after training")
print(weights)

print("Output after training")
print(activated_output)

Weights after training
[[ 1.24900090e-16]
 [-3.05311332e-16]]
Output after training
[[0.5]
 [0.5]
 [0.5]
 [0.5]]


## Implement your own Perceptron Class and use it to classify a binary dataset: 
- [The Pima Indians Diabetes dataset](https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv) 

You may need to search for other's implementations in order to get inspiration for your own. There are *lots* of perceptron implementations on the internet with varying levels of sophistication and complexity. Whatever your approach, make sure you understand **every** line of your implementation and what its purpose is.

In [15]:
diabetes = pd.read_csv('https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv')
diabetes.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

Although neural networks can handle non-normalized data, scaling or normalizing your data will improve your neural network's learning speed. Try to apply the sklearn `MinMaxScaler` or `Normalizer` to your diabetes dataset. 

In [24]:
from sklearn.preprocessing import MinMaxScaler, Normalizer

feats = list(diabetes)[:-1]
feats

X = diabetes.drop(['Outcome'], axis=1)

X_val = X.values
X_val

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [23]:
##### Update this Class #####

class Perceptron():
    
    def __init__(self, niter = 10):
        self.niter = niter
    
    def __sigmoid(self, x):
        return 1 / (1+np.exp(-s))

    
    def __sigmoid_derivative(self, x):
        sx = self.sigmoid(s)
        return sx * (1-sx)

    def fit(self, X, y):
    """Fit training data
    X : Training vectors, X.shape : [#samples, #features]
    y : Target values, y.shape : [#samples]
    """
    # Add bias in term
    X = np.append(X_, np.ones(X_[0]), axis=1)
    
    
    # Randomly Initialize Weights
    self.weights = np.random.random((X.shape[1],1))

    for i in range(self.niter):
        # Weighted sum of inputs / weights
        weighted_sum = np.dot(X, )
        # Activate!

        # Cac error

        # Update the Weights


    def predict(self, X):
    """Return class label after unit step"""
        return None

IndentationError: expected an indented block (<ipython-input-23-4174a8cf5009>, line 20)

## Stretch Goals:

- Research "backpropagation" to learn how weights get updated in neural networks (tomorrow's lecture). 
- Implement a multi-layer perceptron. (for non-linearly separable classes)
- Try and implement your own backpropagation algorithm.
- What are the pros and cons of the different activation functions? How should you decide between them for the different layers of a neural network?